# Generated by Django 4.0.5 on 2022-06-10 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_alter_item_options_alter_item_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
